### ISSUE TITLE
UI: landing page

### ISSUE THREAD

**Issue by johnbelamaric** [nephio-project/one-summit-22-workshop#10]
https://docs.google.com/document/d/1MDCAbPqMYkKyDIMU2q4H4pGnHR9JTinGFJTHrBgUCOs/edit#bookmark=id.cadsidbh81pf

**Comment by ChristopherFry** [comment]
The Config as Data UI landing page has been updated and replaced with a dashboard.

<img width="1413" alt="image" src="https://user-images.githubusercontent.com/4991787/201958614-4ebef5e8-722e-4ab5-8fb1-a65e095b10c5.png">
