### ISSUE TITLE
Overview / drawing of VM, clusters, multus networks, and how NFs connect to them

### ISSUE THREAD

**Issue by johnbelamaric** [nephio-project/one-summit-22-workshop#3]

**Comment by johnbelamaric** [comment]
Vish taking the lead

**Comment by vishwanathj** [comment]
Inputs needed
- How many VMs are we going to be using? At the moment, discussions are to have a single VM
- What would the VM operating system, version and architecture?
- What would be the configurations (CPU, RAM, Storage, networking) of the VM?
- How many KIND clusters are we going to be creating?
- What would be version of KIND that is stable that we would want to deploy?
- How many control plane and worker nodes will each of the KIND cluster have?
- What CNI plugin is needed on each of the KIND clusters?
- What specific requirements do the workloads (SMF/UPF) have for the workload KIND clusters?
- Is Multus required for each of the KIND clusters?
- What would be the networking requirements for the KIND clusters to talk to each other?

**Comment by johnbelamaric** [comment]
I added a free5gc-packages repository for our various free5gc kpt packages we will need for the workshop. This is an additional upstream "external" (read only) repository that will need to be registered with Porch along with nephio-packages.

**Comment by electrocucaracha** [comment]
I'm going to try to answer some of the @vishwanathj questions with the current implementation of the provision [scripts ](https://github.com/nephio-project/one-summit-22-workshop/blob/main/scripts/install.sh)

> NOTE: Given that this is on-progress any of this values can changed.

* How many VMs are we going to be using? At the moment, discussions are to have a single VM
> The terraform [PR ](https://github.com/nephio-project/one-summit-22-workshop/pull/46/files#diff-0658650bb2be59f4fca2fcc55ec1bdf8eb8a0041dc421ace835516c60d3f5a63)indicates one single instance deployed in GCE

* What would the VM operating system, version and architecture?
> I suggest to use `Ubuntu 20.04 LTS (Focal)` but KinD [images](https://github.com/kubernetes-sigs/kind/blob/v0.17.0/images/base/Dockerfile#L22) and Terraform scripts use `Ubuntu 22.04 LTS (Jammy)`, so maybe we can adjust this. The CPU arch is `x86_64` (IMHO dealing with other architectures should be out of the scope for now)

* What would be the configurations (CPU, RAM, Storage, networking) of the VM?
> For the [CI tasks](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources), it's used 2vCPUs, 7 GB of RAM and 14 GB of SSD space. One single network interface.
* How many KIND clusters are we going to be creating?
> The [dynamic list](https://github.com/nephio-project/one-summit-22-workshop/blob/main/scripts/install.sh#L21-L26) provision 3 KinD clusters.
* What would be a version of KIND that is stable that we would want to deploy?
> We're using the latest stable version
```bash
$ kind --version
kind version 0.17.0
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:57:26Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-25T19:35:11Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}
```
* How many control plane and worker nodes will each of the KIND cluster have?
> Those are [deployed ](https://github.com/nephio-project/one-summit-22-workshop/blob/main/scripts/install.sh#L49)as single node cluster. This definition can be [modified ](https://github.com/nephio-project/one-summit-22-workshop/pull/47)but it's important to consider extra cpu and/or memory resources.
* What CNI plugin is needed on each of the KIND clusters?
> It's using the KinD default CNI `kindnetd`. This can be changed as needed. 
  
* What would be the networking requirements for the KIND clusters to talk to each other?
> [Working](https://github.com/nephio-project/one-summit-22-workshop/pull/51) on that

**Comment by johnbelamaric** [comment]
A few comments on this:

* There will be one VM *per participant*.
* The original PR had 3 clusters but I just merged Eric's PR for 4 clusters which matches his design.
* If we can get away with a single node per kind cluster, all the better.
* @electrocucaracha does the cluster inter-connectivity approach you implemented work with Multus?

**Comment by johnbelamaric** [comment]
Oh, and participant VMs are now planned as 8 core 32GB RAM. But the smaller the better for cost reasons. Once we have it all working we can see how small of one we can get away with. The terraform config right now uses Ubuntu 22.04.

**Comment by electrocucaracha** [comment]
>     * @electrocucaracha does the cluster inter-connectivity approach you implemented work with Multus?

No, that approach only creates a container and docker network to interconnect clusters, maybe something similar can be created for Multus Network Definitions.

**Comment by tliron** [comment]
I am working on a solution for the cluster interconnectivity.

**Comment by vjayaramrh** [comment]
A draft PR by @vjayaramrh  to update README is at https://github.com/nephio-project/one-summit-22-workshop/pull/55/files
A PR by @debeaueric that adds a diagram is at https://github.com/nephio-project/one-summit-22-workshop/pull/50
