### ISSUE TITLE
Setup: test the end-to-end workflow, creating a single participant VM and running through the entire workshop

### ISSUE THREAD

**Issue by johnbelamaric** [nephio-project/one-summit-22-workshop#36]

**Comment by vjayaramrh** [comment]
- As an end user, where is the location of the doc or README that describes the steps an end user follows?
- Is the end user expected to create VM? or will it be pre provisioned with VM access details shared?
- Where can I get the inventory of software/packages (docker, git, ansible, go, kind, multus, cni plugins, free5gc operator etc) that needs to either pre-installed or needs to be installed by the end user?
- Is end user expected to create KIND clusters? or will be pre-provisioned?
- What are the steps to deploy the free5gc workload if not already deployed?
- What are the steps to verify successful install of free5gc ?
- What are the steps to be exercised that demonstrate value of Nephio and free5gc?
- What reference links (free5gc, kpt, porch, K8S crds? etc) need to be provided?
