### ISSUE TITLE
Setup: add GitHub access token secret to management cluster

### ISSUE THREAD

**Issue by johnbelamaric** [nephio-project/one-summit-22-workshop#56]
The `workshop` VM already has the secret stored in a file. We will run the scripts from there, and we can copy the file to the new VM when it is created. Then, on the new VM we need to run this command against the management KinD cluster:

`kubectl create secret generic -ndefault github-personal-access-token --from-literal username=nephio-test --from-file password=~/nephio-test-github-pat.txt  --type kubernetes.io/basic-auth`

**Comment by electrocucaracha** [comment]
@johnbelamaric I think those steps have been already implemented:
* [Copying the file](https://github.com/nephio-project/one-summit-22-workshop/blob/main/ansible_kind/kind_setup.yaml#L18) from the `workshop` to the new VM.
* [Registering the secrets on the clusters](https://github.com/nephio-project/one-summit-22-workshop/blob/main/ansible_kind/scripts/multiclusterkind/configure.sh#L31-L36). 
> Maybe this has to be modified to run on a single KinD cluster instead of all of them.
